Repository project-flogo/flogo-web, pull requests merged in 2019-07, with the labels that each got.

#1132 Fix wrong path to default-contrib-bundle file
  apps/server/src/config/app-config.js
  apps/server/src/modules/engine/registry.ts
Labels: area/server, kind/bug

#1133 fix(server): fix db won't persist in dev env
  apps/server/src/configure-engines.ts
  apps/server/src/server.ts
Labels: area/server, kind/bug

#1134 Modals lib
  apps/demo-libs/src/app/modal/modal-content.component.ts
  apps/demo-libs/src/app/modal/modal-demo.module.ts
  apps/demo-libs/src/app/modal/modal-parent.component.html
  apps/demo-libs/src/app/modal/modal-parent.component.less
  apps/demo-libs/src/app/modal/modal-parent.component.ts
  libs/lib-client/modal/README.md
  libs/lib-client/modal/src/components/modal-body/modal-body.component.html
  libs/lib-client/modal/src/components/modal-body/modal-body.component.less
  libs/lib-client/modal/src/components/modal-body/modal-body.component.ts
  libs/lib-client/modal/src/components/modal-footer/modal-footer.component.html
  libs/lib-client/modal/src/components/modal-footer/modal-footer.component.less
  libs/lib-client/modal/src/components/modal-footer/modal-footer.component.ts
  libs/lib-client/modal/src/components/modal-header/modal-header.component.html
  libs/lib-client/modal/src/components/modal-header/modal-header.component.less
  libs/lib-client/modal/src/components/modal-header/modal-header.component.ts
  libs/lib-client/modal/src/components/modal/modal.component.html
  libs/lib-client/modal/src/components/modal/modal.component.less
  libs/lib-client/modal/src/components/modal/modal.component.ts
  libs/lib-client/modal/src/index.ts
  libs/lib-client/modal/src/modal-instance.ts
  libs/lib-client/modal/src/modal.module.ts
  libs/lib-client/modal/src/modal.service.ts
  libs/lib-client/modal/src/variables.less
Labels: area/ui

#1139 feat(stream-client): implement state for streams, integrate header in streams
  apps/client/src/i18n/en.json
  libs/core/src/lib/interfaces/resource.ts
  libs/lib-client/core/src/constants.ts
  libs/lib-client/core/src/interfaces/index.ts
  libs/lib-client/core/src/interfaces/resource.ts
  libs/lib-client/core/src/interfaces/trigger.ts
  libs/lib-client/core/src/models/designer-make-item.ts
  libs/lib-client/core/src/models/designer-parse-metadata.ts
  libs/lib-client/core/src/models/index.ts
  libs/lib-client/core/src/models/normalize-resource-triggers-handlers.ts
  libs/lib-client/core/src/services/restapi/v2/contributions.service.ts
  libs/lib-client/header/src/lib/header.component.less
  libs/plugins/flow-server/src/lib/import/action-importer.spec.ts
  libs/plugins/stream-client/src/lib/core/effects/index.ts
  libs/plugins/stream-client/src/lib/core/effects/stream-save.effects.ts
  libs/plugins/stream-client/src/lib/core/index.ts
  libs/plugins/stream-client/src/lib/core/interfaces/index.ts
  libs/plugins/stream-client/src/lib/core/interfaces/items.ts
  libs/plugins/stream-client/src/lib/core/models/generate-resource-from-state.ts
  libs/plugins/stream-client/src/lib/core/models/generate-state-from-resource.ts
  libs/plugins/stream-client/src/lib/core/models/graph-and-items/graph-creator.ts
  libs/plugins/stream-client/src/lib/core/models/graph-and-items/index.ts
  libs/plugins/stream-client/src/lib/core/models/graph-and-items/items-creator.ts
  libs/plugins/stream-client/src/lib/core/models/graph-and-items/stage-creator.ts
  libs/plugins/stream-client/src/lib/core/models/index.ts
  libs/plugins/stream-client/src/lib/core/state/index.ts
  libs/plugins/stream-client/src/lib/core/state/stream.actions.ts
  libs/plugins/stream-client/src/lib/core/state/stream.reducers.ts
  libs/plugins/stream-client/src/lib/core/state/stream.selectors.ts
  libs/plugins/stream-client/src/lib/core/state/stream.state.ts
  libs/plugins/stream-client/src/lib/core/stream.service.ts
  libs/plugins/stream-client/src/lib/stream-client.module.ts
  libs/plugins/stream-client/src/lib/stream-data.resolver.ts
  libs/plugins/stream-client/src/lib/stream-designer/index.ts
  libs/plugins/stream-client/src/lib/stream-designer/stream-designer.component.html
  libs/plugins/stream-client/src/lib/stream-designer/stream-designer.component.less
  libs/plugins/stream-client/src/lib/stream-designer/stream-designer.component.spec.ts
  libs/plugins/stream-client/src/lib/stream-designer/stream-designer.component.ts
Labels: area/ui, kind/feature

#1140 feat(stream-client): Implement triggers for streams.
  libs/lib-client/core/src/interfaces/index.ts
  libs/lib-client/core/src/interfaces/renderable-trigger.ts
  libs/lib-client/core/src/models/index.ts
  libs/lib-client/core/src/models/triggers-to-renderable-triggers.ts
  libs/plugins/stream-client/src/lib/core/constants.ts
  libs/plugins/stream-client/src/lib/core/index.ts
  libs/plugins/stream-client/src/lib/core/models/generate-state-from-resource.ts
  libs/plugins/stream-client/src/lib/core/models/handler-type.ts
  libs/plugins/stream-client/src/lib/core/models/selection.ts
  libs/plugins/stream-client/src/lib/core/models/stream/selection.ts
  libs/plugins/stream-client/src/lib/core/profile.service.ts
  libs/plugins/stream-client/src/lib/core/state/index.ts
  libs/plugins/stream-client/src/lib/core/state/stream.selectors.ts
  libs/plugins/stream-client/src/lib/core/state/stream.state.ts
  libs/plugins/stream-client/src/lib/core/state/triggers/triggers.actions.ts
  libs/plugins/stream-client/src/lib/core/state/triggers/triggers.reducer.ts
  libs/plugins/stream-client/src/lib/core/state/triggers/triggers.selectors.ts
  libs/plugins/stream-client/src/lib/core/utils.ts
  libs/plugins/stream-client/src/lib/stream-client.module.ts
  libs/plugins/stream-client/src/lib/stream-designer/stream-designer.component.html
  libs/plugins/stream-client/src/lib/triggers/interfaces/triggers-state.ts
  libs/plugins/stream-client/src/lib/triggers/select-trigger/select-trigger.component.html
  libs/plugins/stream-client/src/lib/triggers/select-trigger/select-trigger.component.less
  libs/plugins/stream-client/src/lib/triggers/select-trigger/select-trigger.component.spec.ts
  libs/plugins/stream-client/src/lib/triggers/select-trigger/select-trigger.component.ts
  libs/plugins/stream-client/src/lib/triggers/trigger-block/index.ts
  libs/plugins/stream-client/src/lib/triggers/trigger-block/models.ts
  libs/plugins/stream-client/src/lib/triggers/trigger-block/trigger-block.component.html
  libs/plugins/stream-client/src/lib/triggers/trigger-block/trigger-block.component.less
  libs/plugins/stream-client/src/lib/triggers/trigger-block/trigger-block.component.spec.ts
  libs/plugins/stream-client/src/lib/triggers/trigger-block/trigger-block.component.ts
  libs/plugins/stream-client/src/lib/triggers/triggers.component.html
  libs/plugins/stream-client/src/lib/triggers/triggers.component.less
  libs/plugins/stream-client/src/lib/triggers/triggers.component.ts
  libs/plugins/stream-client/src/lib/triggers/triggers.module.ts
Labels: area/ui, kind/feature
