Repository project-flogo/flogo-web, pull requests merged in 2020-01, with the labels that each got.

#1271 fix: convert single and back quote string to double quote
  libs/plugins/flow-client/src/lib/shared/mapper/utils/mapper-translator.spec.ts
  libs/plugins/flow-client/src/lib/shared/mapper/utils/mapper-translator.ts
  libs/plugins/stream-client/src/lib/shared/mapper/utils/mapper-translator.spec.ts
  libs/plugins/stream-client/src/lib/shared/mapper/utils/mapper-translator.ts
Labels: area/ui, kind/bug

#1278 fix: debug panel inputs were not updated
  libs/plugins/flow-client/src/lib/debug-panel/debug-panel.component.ts
  libs/plugins/flow-client/src/lib/debug-panel/utils.spec.ts
  libs/plugins/flow-client/src/lib/debug-panel/utils.ts
  libs/plugins/flow-client/src/lib/flow.component.ts
  libs/plugins/flow-client/src/lib/shared/dynamic-form/object/object-type.component.html
  libs/plugins/flow-client/src/lib/shared/dynamic-form/object/object-type.component.ts
Labels: area/ui, kind/bug, priority/P0

#1279 Removed master tags for flogo dependencies
  apps/server/src/config/test-engine.config.json
  apps/server/src/init/bootstrap-engine.ts
Labels: area/build-and-ci, area/server
